function cfg = config_envelope_geometry_parameters()
%CONFIG_ENVELOPE_GEOMETRY_PARAMETERS User-editable settings for envelope screening.

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));

cfg.paths.repo_root = repoRoot;
cfg.paths.results_dir = fullfile(repoRoot, 'matlab', 'results', 'envelope_geometry');
cfg.paths.figures_dir = fullfile(repoRoot, 'matlab', 'figures', 'envelope_geometry');

cfg.environment.gravity_m_s2 = 9.81;
cfg.environment.rho_air_kg_m3 = 1.225;
cfg.environment.rho_helium_kg_m3 = 0.164;

cfg.system.reference_mass_g = 35;
cfg.system.target_buoyancy_ratio = 0.90;

cfg.envelope.sigma_ref_kg_m2 = 0.05;

cfg.weights.material_efficiency = 0.35;
cfg.weights.disturbance_response = 0.30;
cfg.weights.spatial_compactness = 0.20;
cfg.weights.practicality = 0.15;
cfg.weights.sum_tolerance = 1.0e-9;

cfg.engineering_significance.material_efficiency_threshold_percent = 5.0;
cfg.engineering_significance.disturbance_threshold_percent = 10.0;
cfg.engineering_significance.footprint_threshold_percent = 10.0;
cfg.engineering_significance.score_difference_threshold_percent = 5.0;

cfg.practicality.acceptable_score_max = 4.0;

cfg.constraints.apply_size_limits = false;
cfg.constraints.max_length_m = inf;
cfg.constraints.max_width_m = inf;
cfg.constraints.max_height_m = inf;
cfg.constraints.max_dimension_m = inf;

cfg.sensitivity.mass_g = 25:5:60;
cfg.sensitivity.buoyancy_ratio = 0.70:0.05:1.00;
cfg.sensitivity.surface_density_kg_m2 = [0.03, 0.05, 0.08];

cfg.statistics.enable_supplementary_anova = true;
cfg.statistics.anova_alpha = 0.05;

cfg.output.write_debug_tables = false;
cfg.output.write_debug_figures = false;

cfg.shapes = [ ...
    struct( ...
        'name', "sphere", ...
        'display_name', "Sphere", ...
        'type', "sphere", ...
        'aspect_ratio', [1.0 1.0 1.0], ...
        'cd_xyz', [0.90 0.90 0.90], ...
        'manufacturability_score', 1, ...
        'availability_score', 1, ...
        'practical_score_source', "commercial availability"), ...
    struct( ...
        'name', "prolate_ellipsoid", ...
        'display_name', "Prolate Ellipsoid", ...
        'type', "ellipsoid", ...
        'aspect_ratio', [1.8 1.0 1.0], ...
        'cd_xyz', [0.65 0.95 0.95], ...
        'manufacturability_score', 3, ...
        'availability_score', 3, ...
        'practical_score_source', "assumption"), ...
    struct( ...
        'name', "cuboid", ...
        'display_name', "Cuboid", ...
        'type', "cuboid", ...
        'aspect_ratio', [1.0 1.0 1.0], ...
        'cd_xyz', [1.00 1.00 1.00], ...
        'manufacturability_score', 4, ...
        'availability_score', 4, ...
        'practical_score_source', "manufacturing complexity estimate"), ...
    struct( ...
        'name', "flattened_ellipsoid", ...
        'display_name', "Flattened Ellipsoid", ...
        'type', "ellipsoid", ...
        'aspect_ratio', [1.6 1.3 0.7], ...
        'cd_xyz', [0.82 0.92 1.08], ...
        'manufacturability_score', 4, ...
        'availability_score', 4, ...
        'practical_score_source', "manufacturing complexity estimate") ...
    ];

end